### ISSUE TITLE
.

### ISSUE THREAD

**Issue by JakDaxe** [LucianoDeveloper/economy-bot#2]
.

**Comment by KamaiDev** [comment]
Sim, qual a dúvida? Não estou fazendo o uso do discord pois perdi meu
aparelho celular e o acesso a minha conta. Caso seja de preferência, pode
enviar um email de resposta com sua dúvida e eu responderei.

Em qui., 16 de jul. de 2020 às 17:00, jakDAX <notifications@github.com>
escreveu:

**Comment by JakDeabel** [comment]
Eu fiz tudo direitinho e quando uso um comando dá um erro talvez voce saiba o porque?

![image](https://user-images.githubusercontent.com/44744872/87739017-abf35080-c7d6-11ea-81ea-d36a2100c207.png)

**Comment by KamaiDev** [comment]
"cache" não foi definido. Isso pode ter ocorrido pois a versão da sua (
discord.js ) não está atualizada, então caso prefira continuar na versão
11, basta apagar todos os ".cache" do código. Mas caso deseja usar a versão
recente, basta atualizar a ( discord.js ) para a versão 12 que funcionará
normalmente.

Em qui., 16 de jul. de 2020 às 22:39, jakDAX <notifications@github.com>
escreveu:

**Comment by JakDeabel** [comment]
mas eu tou usando versão 12.....
